In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [2]:
x = pd.read_csv('x.csv', header = None)
y = pd.read_csv('y.csv', header = None)
x1 = pd.read_csv('x1.csv', header = None)
x = np.array(x)
x1 = np.array(x1)
y = np.array(y)
y = y.reshape(y.shape[0])

x = x.reshape(297146, 29, 1)
x1 = x1.reshape(297146, 29, 1)
new_x = np.concatenate((x,x1), axis = 2)

In [3]:
new_x.shape

(297146, 29, 2)

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(new_x, y, test_size = 0.05, random_state = 64)

In [5]:
x_train.shape, y_train.shape

((282288, 29, 2), (282288,))

### ADAMAX

In [7]:
classifier = Sequential()

classifier.add(LSTM(units = 128, return_sequences = True, input_shape = (x_train.shape[1], 2)))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128))
classifier.add(Dropout(0.2))

classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 32, activation = 'relu'))
classifier.add(Dense(units = 1))

classifier.compile(optimizer = 'adamax', loss = 'binary_crossentropy')

In [8]:
classifier.fit(x_train, y_train, epochs = 5, batch_size = 64, workers = 6)

Epoch 1/5
4411/4411 [==============================] - 515s 117ms/step - loss: 0.6695
Epoch 2/5
4411/4411 [==============================] - 565s 128ms/step - loss: 0.6586
Epoch 3/5
4411/4411 [==============================] - 544s 123ms/step - loss: 0.6557
Epoch 4/5
4411/4411 [==============================] - 545s 124ms/step - loss: 0.6549
Epoch 5/5
4411/4411 [==============================] - 549s 124ms/step - loss: 0.6543


In [9]:
y_pred = classifier.predict(x_test)
y_pred_rounded = []
for i in y_pred:
    if i >= 0.5:
        y_pred_rounded.append(1)
    else:
        y_pred_rounded.append(0)
y_pred_rounded = np.array(y_pred_rounded)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test, y_pred_rounded)

array([[3987, 3472],
       [2272, 5127]], dtype=int64)

In [11]:
accuracy_score(y_test, y_pred_rounded)

0.6134069188316059

### ADAM

In [7]:
classifier = Sequential()

classifier.add(LSTM(units = 128, return_sequences = True, input_shape = (x_train.shape[1], 2)))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128))
classifier.add(Dropout(0.2))

classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 32, activation = 'relu'))
classifier.add(Dense(units = 1))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy')

In [8]:
classifier.fit(x_train, y_train, epochs = 5, batch_size = 64, workers = 6)

Epoch 1/5
4411/4411 [==============================] - 477s 108ms/step - loss: 0.6665
Epoch 2/5
4411/4411 [==============================] - 486s 110ms/step - loss: 0.6575
Epoch 3/5
4411/4411 [==============================] - 501s 114ms/step - loss: 0.6560
Epoch 4/5
4411/4411 [==============================] - 507s 115ms/step - loss: 0.6552
Epoch 5/5
4411/4411 [==============================] - 512s 116ms/step - loss: 0.6543


In [9]:
y_pred = classifier.predict(x_test)
y_pred_rounded = []
for i in y_pred:
    if i >= 0.5:
        y_pred_rounded.append(1)
    else:
        y_pred_rounded.append(0)
y_pred_rounded = np.array(y_pred_rounded)
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test, y_pred_rounded)

array([[3579, 3880],
       [1954, 5445]], dtype=int64)

In [10]:
accuracy_score(y_test, y_pred_rounded)

0.6073495759860008

### Full Adam

In [7]:
classifier = Sequential()

classifier.add(LSTM(units = 128, return_sequences = True, input_shape = (x_train.shape[1], 2)))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128, return_sequences = True))
classifier.add(Dropout(0.2))

classifier.add(LSTM(units = 128))
classifier.add(Dropout(0.2))

classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 32, activation = 'relu'))
classifier.add(Dense(units = 1))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy')

In [8]:
classifier.fit(x_train, y_train, epochs = 100, batch_size = 64, workers = 6)

Epoch 1/100
4411/4411 [==============================] - 576s 131ms/step - loss: 0.6651
Epoch 2/100
4411/4411 [==============================] - 614s 139ms/step - loss: 0.6578
Epoch 3/100
4411/4411 [==============================] - 606s 137ms/step - loss: 0.6562
Epoch 4/100
4411/4411 [==============================] - 574s 130ms/step - loss: 0.6552
Epoch 5/100
4411/4411 [==============================] - 617s 140ms/step - loss: 0.6543
Epoch 6/100
4411/4411 [==============================] - 648s 147ms/step - loss: 0.6537
Epoch 7/100
4411/4411 [==============================] - 623s 141ms/step - loss: 0.6535
Epoch 8/100
4411/4411 [==============================] - 650s 147ms/step - loss: 0.6530
Epoch 9/100
4411/4411 [==============================] - 677s 153ms/step - loss: 0.6527
Epoch 10/100
4411/4411 [==============================] - 633s 144ms/step - loss: 0.6524
Epoch 11/100
4411/4411 [==============================] - 647s 147ms/step - loss: 0.6522
Epoch 12/100
4411/4411 [======

KeyboardInterrupt: 

In [9]:
y_pred = classifier.predict(x_test)
y_pred_rounded = []
for i in y_pred:
    if i >= 0.5:
        y_pred_rounded.append(1)
    else:
        y_pred_rounded.append(0)
y_pred_rounded = np.array(y_pred_rounded)
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test, y_pred_rounded)

array([[4111, 3348],
       [2413, 4986]], dtype=int64)

In [10]:
accuracy_score(y_test, y_pred_rounded)

0.6122627540718805